# Generated by Django 5.2.5 on 2025-08-18 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('oficial_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('paralelo_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('differential', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_dashboard.client')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_dashboard.area')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('engagement_partner', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('collections', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('billing', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bcv_rate', models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=10, null=True)),
                ('monitor_rate', models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=10, null=True)),
                ('engagement_id', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_service_line', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_sub_service_line', models.CharField(blank=True, max_length=255, null=True)),
                ('fytd_charged_hours', models.FloatField(blank=True, default=0.0, null=True)),
                ('fytd_direct_cost_amt', models.FloatField(blank=True, default=0.0, null=True)),
                ('fytd_ansr_amt', models.FloatField(blank=True, default=0.0, null=True)),
                ('mtd_charged_hours', models.FloatField(blank=True, default=0.0, null=True)),
                ('mtd_direct_cost_amt', models.FloatField(blank=True, default=0.0, null=True)),
                ('mtd_ansr_amt', models.FloatField(blank=True, default=0.0, null=True)),
                ('cp_ansr_amt', models.FloatField(blank=True, default=0.0, null=True)),
                ('duplicate_engagement_id', models.IntegerField(blank=True, default=0, null=True)),
                ('original_week_string', models.CharField(blank=True, max_length=255, null=True)),
                ('periodo_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_cobro', models.CharField(blank=True, max_length=255, null=True)),
                ('dif_div', models.FloatField(blank=True, null=True)),
                ('perdida_tipo_cambio_monitor', models.FloatField(blank=True, null=True)),
                ('fytd_diferencial_final', models.FloatField(blank=True, null=True)),
                ('fytd_ansr_sintetico', models.FloatField(blank=True, null=True)),
                ('total_revenue_days_p_cp', models.FloatField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_dashboard.area')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_dashboard.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_dashboard.contract')),
                ('sub_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_dashboard.subarea')),
            ],
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
