# Generated by Django 5.2.5 on 2025-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0002_revenueentry_diferencial_mtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueentry',
            name='fytd_ar_collected_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='fytd_ar_collected_tax_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='fytd_collect_total_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
