# Generated by Django 5.2.5 on 2025-09-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0003_revenueentry_fytd_ar_collected_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueentry',
            name='fytd_total_billed_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
