# Generated by Django 5.2.5 on 2025-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0004_revenueentry_fytd_total_billed_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerRevenueDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_line', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_service_line', models.CharField(blank=True, max_length=255, null=True)),
                ('revenue_days', models.FloatField(blank=True, default=0.0, null=True)),
                ('engagement_id', models.CharField(blank=True, max_length=255, null=True)),
                ('week_ending', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Manager Revenue Days',
                'verbose_name_plural': 'Manager Revenue Days',
                'unique_together': {('date', 'manager_name', 'engagement_name')},
            },
        ),
    ]
