# Generated by Django 5.2.5 on 2025-09-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0005_managerrevenuedays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerRevenueDays',
        ),
    ]
